image: gcc:4.8

stages:
        - build
        - test
        - deploy

cache:
        paths:
                - build/

job_build:
        stage: build

        only: 
                - master

        before_script:
                # Prepare l'environnement "Travis"
                - mkdir -p /home/travis
                - ln -s /usr/local/bin /home/travis/bin
                - env
                # Travis before_install
                - apt-get update
                - apt-get install -qq git
                - apt-get install -qq unzip
                - pushd ..
                - git clone https://github.com/assinie/md2hlp.git
                - git clone https://github.com/cc65/cc65.git
                - cd cc65 && make &> /dev/null
                - cp bin/* /home/travis/bin/
                - popd

        script:
                # Simule le fonctionnement de travis
                - ./configure && make && make test

        artifacts:
                expire_in: 1 hour
                paths:
                    - build/


job_test:
        stage: test

        only:
                - master

        cache:
                policy: pull

        script:
                - ls

job_deploy:
        stage: deploy

        only:
                - master

        cache:
                policy: pull

        script:
                - ls -Rlh


